### ISSUE TITLE
Is there a simplified version of this with the RGB code removed?

### ISSUE THREAD

**Issue by chowder3907** [speedypotato/Pico-Game-Controller#30]
I'm looking to use this code in a guitar hero guitar which I need the code to be very fast and optimized for. Would you be willing to make/help me make a version of this with the RGB removed? You can contact me at chowder3907@protonmail.com or just respond here

**Comment by speedypotato** [comment]
Pi Pico's RP2040 is a dual core MCU, and in pico-game-controller one core is for RGB while the other is for handling inputs.  RGB adds no performance penalty as a result.

**Comment by chowder3907** [comment]
ah beautiful, thank you
