### ISSUE TITLE
Is there a way to make this output from the two UART pins?

### ISSUE THREAD

**Issue by chowder3907** [speedypotato/Pico-Game-Controller#31]
H it's me again lol. I'm looking at the cmake files and don't see a way to make it choose if it's ouputting via the USB port or the two UART pins on pins 21 and 22. Is there an easy way to change this or is it baked pretty deep into the code?

**Comment by speedypotato** [comment]
There's no UART in this controller.  You'll probably have to add it yourself.  Haven't done UART myself either so it's probably time for you to take a look at docs https://raspberrypi.github.io/pico-sdk-doxygen/group__hardware__uart.html
