### ISSUE TITLE
pinout of premade images

### ISSUE THREAD

**Issue by turbotorsion420** [speedypotato/Pico-Game-Controller#43]
would it be possible to show what the correct pinout for the precompiled images?
i'm trying to figure it out by looking through the source code and while finding most of the required gpio pins, i'm still unsure of where the rotary encoders hook up to

**Comment by speedypotato** [comment]
controller_config.h shows all the gpio pins.  The encoder gpio pins are sequential, so if you see 0 defined, it'll be 0, 1 as an example.

This firmware is meant to be customized to your needs, with pocket-sdvx-#### and pocket-iidx branches being examples of customizations and good starting off points for other projects.
