### ISSUE TITLE
Button 8 Keep pressing

### ISSUE THREAD

**Issue by LucaSoranota** [speedypotato/Pico-Game-Controller#44]
![image](https://github.com/user-attachments/assets/d78465fa-0e36-4a50-bd5a-4c0b76cdcf42)

as the title said
this makes the controller cannot be remapped in certain BMS players, especially bemuse
some bms player are very hard to remap buat its possible like Qwilight

is there a fix?

thanks

**Comment by speedypotato** [comment]
This is probably a hardware issue on your side, I've had multiple people test pocket-iidx branch without issue.
